// src/admin/constants/activityLogsData.js
import {
  ShoppingBag,
  UtensilsCrossed,
  Users,
  Settings,
  Trash2,
  LogIn,
  Pencil,
  Plus,
} from "lucide-react";

export const actionTypes = ["All", "Created", "Updated", "Deleted", "Login"];

export const activityLogsData = [
  {
    id: 1,
    user: "Sana Tariq",
    role: "Manager",
    action: "Updated",
    module: "Orders",
    description: "Updated status of ORD-10284 to 'Preparing'",
    icon: Pencil,
    time: "2 min ago",
    date: "2026-07-19",
  },
  {
    id: 2,
    user: "Admin Khan",
    role: "Super Admin",
    action: "Deleted",
    module: "Products",
    description: "Deleted product 'Old Special Pizza'",
    icon: Trash2,
    time: "15 min ago",
    date: "2026-07-19",
  },
  {
    id: 3,
    user: "Sana Tariq",
    role: "Manager",
    action: "Created",
    module: "Coupons",
    description: "Created new coupon 'WEEKEND100'",
    icon: Plus,
    time: "1 hr ago",
    date: "2026-07-19",
  },
  {
    id: 4,
    user: "Zainab Fatima",
    role: "Cashier",
    action: "Login",
    module: "System",
    description: "Logged in from 192.168.1.24",
    icon: LogIn,
    time: "3 hrs ago",
    date: "2026-07-19",
  },
  {
    id: 5,
    user: "Admin Khan",
    role: "Super Admin",
    action: "Updated",
    module: "Settings",
    description: "Changed tax percentage from 3% to 5%",
    icon: Settings,
    time: "5 hrs ago",
    date: "2026-07-19",
  },
  {
    id: 6,
    user: "Sana Tariq",
    role: "Manager",
    action: "Created",
    module: "Products",
    description: "Added new product 'Zinger Burger'",
    icon: UtensilsCrossed,
    time: "1 day ago",
    date: "2026-07-18",
  },
  {
    id: 7,
    user: "Admin Khan",
    role: "Super Admin",
    action: "Deleted",
    module: "Customers",
    description: "Removed customer account 'test@example.com'",
    icon: Users,
    time: "1 day ago",
    date: "2026-07-18",
  },
  {
    id: 8,
    user: "Zainab Fatima",
    role: "Cashier",
    action: "Updated",
    module: "Orders",
    description: "Marked ORD-10279 as 'Cancelled'",
    icon: ShoppingBag,
    time: "2 days ago",
    date: "2026-07-17",
  },
];
