import {
  ShoppingBag,
  Clock,
  ChefHat,
  CheckCircle2,
  XCircle,
  DollarSign,
  TrendingUp,
  Users,
  UtensilsCrossed,
  LayoutGrid,
  AlertTriangle,
} from "lucide-react";

export const statsData = [
  {
    id: "total-orders",
    label: "Total Orders",
    value: "12,847",
    change: "12.4%",
    trend: "up",
    icon: ShoppingBag,
    color: "rose",
  },
  {
    id: "today-orders",
    label: "Today's Orders",
    value: "184",
    change: "8.1%",
    trend: "up",
    icon: Clock,
    color: "blue",
  },
  {
    id: "pending",
    label: "Pending",
    value: "23",
    change: null,
    trend: null,
    icon: Clock,
    color: "amber",
  },
  {
    id: "preparing",
    label: "Preparing",
    value: "14",
    change: null,
    trend: null,
    icon: ChefHat,
    color: "sky",
  },
  {
    id: "delivered",
    label: "Delivered",
    value: "11,928",
    change: "3.2%",
    trend: "up",
    icon: CheckCircle2,
    color: "green",
  },
  {
    id: "cancelled",
    label: "Cancelled",
    value: "342",
    change: "1.1%",
    trend: "down",
    icon: XCircle,
    color: "red",
  },
  {
    id: "total-revenue",
    label: "Total Revenue",
    value: "Rs 458,920",
    change: "18.6%",
    trend: "up",
    icon: DollarSign,
    color: "rose",
  },
  {
    id: "today-revenue",
    label: "Today's Revenue",
    value: "Rs 6,420",
    change: "6.4%",
    trend: "up",
    icon: TrendingUp,
    color: "green",
  },
  {
    id: "total-customers",
    label: "Total Customers",
    value: "3,421",
    change: "4.7%",
    trend: "up",
    icon: Users,
    color: "sky",
  },
  {
    id: "total-products",
    label: "Total Products",
    value: "87",
    change: null,
    trend: null,
    icon: UtensilsCrossed,
    color: "stone",
  },
  {
    id: "categories",
    label: "Categories",
    value: "8",
    change: null,
    trend: null,
    icon: LayoutGrid,
    color: "stone",
  },
  {
    id: "low-stock",
    label: "Low Stock Items",
    value: "6",
    change: null,
    trend: null,
    icon: AlertTriangle,
    color: "red",
  },
];

export const monthlySalesData = [
  { month: "Jan", revenue: 25000 },
  { month: "Feb", revenue: 27500 },
  { month: "Mar", revenue: 26000 },
  { month: "Apr", revenue: 32000 },
  { month: "May", revenue: 38000 },
  { month: "Jun", revenue: 37000 },
  { month: "Jul", revenue: 39500 },
  { month: "Aug", revenue: 43000 },
  { month: "Sep", revenue: 40000 },
  { month: "Oct", revenue: 45000 },
  { month: "Nov", revenue: 50000 },
  { month: "Dec", revenue: 58000 },
];

export const weeklyOrdersData = [
  { day: "Mon", orders: 145 },
  { day: "Tue", orders: 160 },
  { day: "Wed", orders: 140 },
  { day: "Thu", orders: 175 },
  { day: "Fri", orders: 205 },
  { day: "Sat", orders: 290 },
  { day: "Sun", orders: 260 },
];

export const revenueThisMonthData = [
  { day: "01", revenue: 4200 },
  { day: "05", revenue: 4900 },
  { day: "10", revenue: 4500 },
  { day: "15", revenue: 6100 },
  { day: "20", revenue: 5600 },
  { day: "25", revenue: 7200 },
  { day: "30", revenue: 6900 },
];

export const topSellingProducts = [
  { id: 1, name: "Pepperoni Feast", sold: 1284 },
  { id: 2, name: "Chicken Tikka", sold: 1102 },
  { id: 3, name: "BBQ Beef", sold: 942 },
  { id: 4, name: "Margherita Classic", sold: 812 },
  { id: 5, name: "Veggie Supreme", sold: 684 },
  { id: 6, name: "Hawaiian", sold: 542 },
];

export const latestOrders = [
  {
    id: "ORD-10284",
    customer: "Ali Khan",
    items: 3,
    payment: "COD",
    time: "2 min ago",
    amount: "Rs 2,450",
    status: "Preparing",
  },
  {
    id: "ORD-10283",
    customer: "Sara Ahmed",
    items: 2,
    payment: "Card",
    time: "5 min ago",
    amount: "Rs 1,780",
    status: "Pending",
  },
  {
    id: "ORD-10282",
    customer: "Bilal Hussain",
    items: 4,
    payment: "JazzCash",
    time: "12 min ago",
    amount: "Rs 3,200",
    status: "Out for Delivery",
  },
  {
    id: "ORD-10281",
    customer: "Ayesha Malik",
    items: 1,
    payment: "COD",
    time: "24 min ago",
    amount: "Rs 890",
    status: "Delivered",
  },
  {
    id: "ORD-10280",
    customer: "Hamza Sheikh",
    items: 5,
    payment: "Card",
    time: "38 min ago",
    amount: "Rs 4,120",
    status: "Delivered",
  },
  {
    id: "ORD-10279",
    customer: "Fatima Noor",
    items: 2,
    payment: "EasyPaisa",
    time: "1 hr ago",
    amount: "Rs 1,560",
    status: "Cancelled",
  },
];

export const newCustomers = [
  { id: 1, name: "Ali Khan", orders: 24, spent: "Rs 38,240" },
  { id: 2, name: "Sara Ahmed", orders: 18, spent: "Rs 27,180" },
  { id: 3, name: "Bilal Hussain", orders: 12, spent: "Rs 19,420" },
  { id: 4, name: "Ayesha Malik", orders: 8, spent: "Rs 11,890" },
];

export const latestReviews = [
  {
    id: 1,
    name: "Ali Khan",
    rating: 5,
    comment: "Best pizza in town, always fresh!",
    product: "Pepperoni Feast",
  },
  {
    id: 2,
    name: "Sara Ahmed",
    rating: 4,
    comment: "Great flavor, delivery was quick.",
    product: "Chicken Tikka",
  },
  {
    id: 3,
    name: "Bilal Hussain",
    rating: 5,
    comment: "Loaded with toppings, loved it.",
    product: "BBQ Beef",
  },
];