// src/admin/constants/deliveryBoysData.js
export const vehicleTypes = ["All", "Bike", "Car", "Bicycle"];

export const deliveryBoysData = [
  {
    id: 1,
    name: "Kamran Shah",
    phone: "0300-9988776",
    vehicle: "Bike",
    vehicleNumber: "SGD-1234",
    status: "available",
    activeOrders: 0,
    totalDeliveries: 342,
    rating: 4.8,
  },
  {
    id: 2,
    name: "Waqas Ahmed",
    phone: "0321-8877665",
    vehicle: "Bike",
    vehicleNumber: "SGD-5678",
    status: "on_delivery",
    activeOrders: 2,
    totalDeliveries: 218,
    rating: 4.5,
  },
  {
    id: 3,
    name: "Rizwan Malik",
    phone: "0333-7766554",
    vehicle: "Car",
    vehicleNumber: "SGD-9012",
    status: "available",
    activeOrders: 0,
    totalDeliveries: 156,
    rating: 4.9,
  },
  {
    id: 4,
    name: "Faisal Khan",
    phone: "0345-6655443",
    vehicle: "Bike",
    vehicleNumber: "SGD-3456",
    status: "on_delivery",
    activeOrders: 1,
    totalDeliveries: 289,
    rating: 4.6,
  },
  {
    id: 5,
    name: "Tariq Javed",
    phone: "0312-5544332",
    vehicle: "Bicycle",
    vehicleNumber: "—",
    status: "offline",
    activeOrders: 0,
    totalDeliveries: 87,
    rating: 4.2,
  },
];
