// src/admin/constants/employeesData.js
export const employeeRoles = [
  "All",
  "Chef",
  "Waiter",
  "Cashier",
  "Manager",
  "Kitchen Helper",
];

export const employeesData = [
  {
    id: 1,
    name: "Ahmed Raza",
    role: "Chef",
    phone: "0300-1112233",
    email: "ahmed.raza@sarab.com",
    shift: "Morning (8AM-4PM)",
    joinDate: "2025-03-15",
    status: "active",
  },
  {
    id: 2,
    name: "Sana Tariq",
    role: "Manager",
    phone: "0321-2223344",
    email: "sana.tariq@sarab.com",
    shift: "Full Day (9AM-6PM)",
    joinDate: "2024-11-01",
    status: "active",
  },
  {
    id: 3,
    name: "Usman Ali",
    role: "Waiter",
    phone: "0333-3334455",
    email: "usman.ali@sarab.com",
    shift: "Evening (4PM-12AM)",
    joinDate: "2025-06-20",
    status: "active",
  },
  {
    id: 4,
    name: "Zainab Fatima",
    role: "Cashier",
    phone: "0345-4445566",
    email: "zainab.f@sarab.com",
    shift: "Morning (8AM-4PM)",
    joinDate: "2025-01-10",
    status: "active",
  },
  {
    id: 5,
    name: "Bilal Ahmed",
    role: "Kitchen Helper",
    phone: "0312-5556677",
    email: "bilal.a@sarab.com",
    shift: "Evening (4PM-12AM)",
    joinDate: "2025-08-05",
    status: "inactive",
  },
  {
    id: 6,
    name: "Hina Malik",
    role: "Waiter",
    phone: "0301-6667788",
    email: "hina.malik@sarab.com",
    shift: "Full Day (9AM-6PM)",
    joinDate: "2025-04-22",
    status: "active",
  },
];
