// src/admin/constants/inventoryData.js
export const inventoryData = [
  {
    id: 1,
    name: "Pepperoni Feast",
    category: "Pizza",
    stock: 42,
    reorderLevel: 15,
    unit: "pcs",
    lastRestocked: "2026-07-10",
  },
  {
    id: 2,
    name: "Chicken Tikka Pizza",
    category: "Pizza",
    stock: 30,
    reorderLevel: 15,
    unit: "pcs",
    lastRestocked: "2026-07-12",
  },
  {
    id: 3,
    name: "Beef BBQ Burger",
    category: "Burgers",
    stock: 55,
    reorderLevel: 20,
    unit: "pcs",
    lastRestocked: "2026-07-13",
  },
  {
    id: 4,
    name: "Zinger Burger",
    category: "Burgers",
    stock: 5,
    reorderLevel: 20,
    unit: "pcs",
    lastRestocked: "2026-07-08",
  },
  {
    id: 5,
    name: "Chocolate Lava Cake",
    category: "Desserts",
    stock: 20,
    reorderLevel: 10,
    unit: "pcs",
    lastRestocked: "2026-07-11",
  },
  {
    id: 6,
    name: "Mango Milkshake",
    category: "Beverages",
    stock: 0,
    reorderLevel: 15,
    unit: "pcs",
    lastRestocked: "2026-07-05",
  },
  {
    id: 7,
    name: "Cheese Slices",
    category: "Raw Material",
    stock: 8,
    reorderLevel: 25,
    unit: "kg",
    lastRestocked: "2026-07-09",
  },
];
