// src/admin/constants/ordersData.js
export const orderStatuses = [
  "All",
  "Pending",
  "Preparing",
  "Out for Delivery",
  "Delivered",
  "Cancelled",
];

export const ordersData = [
  {
    id: "ORD-10284",
    customer: "Ali Khan",
    phone: "0300-1234567",
    address: "House 12, Street 5, Sargodha",
    items: [
      { name: "Pepperoni Feast", qty: 2, price: 1450 },
      { name: "Mango Milkshake", qty: 1, price: 350 },
    ],
    total: 3250,
    payment: "COD",
    status: "Preparing",
    date: "2026-07-15",
    time: "2 min ago",
  },
  {
    id: "ORD-10283",
    customer: "Sara Ahmed",
    phone: "0321-9876543",
    address: "Flat 3B, Model Town, Sargodha",
    items: [{ name: "Chicken Tikka Pizza", qty: 1, price: 1550 }],
    total: 1550,
    payment: "Card",
    status: "Pending",
    date: "2026-07-15",
    time: "5 min ago",
  },
  {
    id: "ORD-10282",
    customer: "Bilal Hussain",
    phone: "0333-4567891",
    address: "House 45, Satellite Town, Sargodha",
    items: [
      { name: "Beef BBQ Burger", qty: 2, price: 850 },
      { name: "Zinger Burger", qty: 1, price: 750 },
      { name: "Chocolate Lava Cake", qty: 1, price: 450 },
    ],
    total: 2900,
    payment: "JazzCash",
    status: "Out for Delivery",
    date: "2026-07-15",
    time: "12 min ago",
  },
  {
    id: "ORD-10281",
    customer: "Ayesha Malik",
    phone: "0345-1122334",
    address: "House 7, Civil Lines, Sargodha",
    items: [{ name: "Mango Milkshake", qty: 2, price: 350 }],
    total: 700,
    payment: "COD",
    status: "Delivered",
    date: "2026-07-15",
    time: "24 min ago",
  },
  {
    id: "ORD-10280",
    customer: "Hamza Sheikh",
    phone: "0312-5566778",
    address: "House 22, Race Course Road, Sargodha",
    items: [
      { name: "Pepperoni Feast", qty: 1, price: 1450 },
      { name: "Beef BBQ Burger", qty: 3, price: 850 },
    ],
    total: 4000,
    payment: "Card",
    status: "Delivered",
    date: "2026-07-15",
    time: "38 min ago",
  },
  {
    id: "ORD-10279",
    customer: "Fatima Noor",
    phone: "0301-9988776",
    address: "House 3, Farooq Colony, Sargodha",
    items: [{ name: "Zinger Burger", qty: 2, price: 750 }],
    total: 1500,
    payment: "EasyPaisa",
    status: "Cancelled",
    date: "2026-07-15",
    time: "1 hr ago",
  },
];
