// src/admin/constants/reviewsData.js
export const reviewsData = [
  {
    id: 1,
    customer: "Ali Khan",
    rating: 5,
    comment: "Best pizza in town, always fresh and delivered hot!",
    product: "Pepperoni Feast",
    date: "2026-07-14",
    status: "approved",
  },
  {
    id: 2,
    customer: "Sara Ahmed",
    rating: 4,
    comment: "Great flavor, delivery was quick. Will order again.",
    product: "Chicken Tikka Pizza",
    date: "2026-07-13",
    status: "approved",
  },
  {
    id: 3,
    customer: "Bilal Hussain",
    rating: 5,
    comment: "Loaded with toppings, loved it. Highly recommend.",
    product: "BBQ Beef Burger",
    date: "2026-07-12",
    status: "approved",
  },
  {
    id: 4,
    customer: "Ayesha Malik",
    rating: 2,
    comment: "Order arrived late and was a bit cold.",
    product: "Zinger Burger",
    date: "2026-07-11",
    status: "pending",
  },
  {
    id: 5,
    customer: "Hamza Sheikh",
    rating: 3,
    comment: "Taste was okay, expected more toppings for the price.",
    product: "Margherita Classic",
    date: "2026-07-10",
    status: "pending",
  },
  {
    id: 6,
    customer: "Fatima Noor",
    rating: 5,
    comment: "Amazing dessert, perfect ending to the meal!",
    product: "Chocolate Lava Cake",
    date: "2026-07-09",
    status: "approved",
  },
];
